Don't require pydot for Python tests
Summary:
Working towards https://github.com/caffe2/caffe2/pull/817.
```
>       graph = pydot.Dot(name, rankdir=rankdir)
E       AttributeError: 'NoneType' object has no attribute 'Dot'
```
https://travis-ci.org/caffe2/caffe2/jobs/243867951
Closes https://github.com/caffe2/caffe2/pull/827

Differential Revision: D5276691

Pulled By: akyrola

fbshipit-source-id: 047ee869c029002ace29d84c6b56534b7f23f87b