fix minor bug, message variable does not exist (#46777)
Summary:
When run with `--continue-through-error`, the script ends with the following error:

```
Traceback (most recent call last):
  File "run_test.py", line 745, in <module>
    main()
  File "run_test.py", line 741, in main
    print_to_stderr(message)
NameError: name 'message' is not defined
make: *** [macos-compat] Error 1
```

This PR just changes `message` to `err`, which is the intended variable.

Pull Request resolved: https://github.com/pytorch/pytorch/pull/46777

Reviewed By: seemethere

Differential Revision: D24510460

Pulled By: janeyx99

fbshipit-source-id: be1124b6fc72b178d62acc168d0cbc74962de52b